[package]
name = "enums"
version = "0.0.1"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
edition = "2018"
build = "../build.rs"

[build-dependencies]
cc = "^1.0"
phf_codegen = "^0.7"

[dependencies]
tree-sitter = "^0.3"
enum-iterator = "^0.3"
clap = "^2.33"
askama = "^0.8"
phf_codegen = "^0.7"
libc = "^0.2"